In [26]:
import pandas as pd

pd.set_option('display.max_columns', None)

pd.set_option('display.max_rows', 100)

df1 = pd.read_csv('./raw_data/GlobalAirportDatabase.csv')

df1

,ICAO Code,IATA Code,Airport Name,City/Town,Country,Latitude Degrees,Latitude Minutes,Latitude Seconds,Latitude Direction,Longitude Degrees,Longitude Minutes,Longitude Seconds,Longitude Direction,Altitude,Latitude Decimal Degrees,Longitude Decimal Degrees
0,AYGA,GKA,GOROKA,GOROKA,PAPUA NEW GUINEA,6,4,54,S,145,23,30,E,1610,-6.082,145.392
1,AYLA,LAE,NaN,LAE,PAPUA NEW GUINEA,0,0,0,U,0,0,0,U,0,0.000,0.000
2,AYMD,MAG,MADANG,MADANG,PAPUA NEW GUINEA,5,12,25,S,145,47,19,E,7,-5.207,145.789
3,AYMH,HGU,MOUNT HAGEN,MOUNT HAGEN,PAPUA NEW GUINEA,5,49,34,S,144,17,46,E,1643,-5.826,144.296
4,AYNZ,LAE,NADZAB,NADZAB,PAPUA NEW GUINEA,6,34,11,S,146,43,34,E,73,-6.570,146.726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9295,ZYTK,NaN,NaN,SHENYANG,CHINA,0,0,0,U,0,0,0,U,0,0.000,0.000
9296,ZYTL,DLC,ZHOUSHUIZI,DALIAN,CHINA,38,57,56,N,121,32,18,E,33,38.966,121.538
9297,ZYXC,NaN,NaN,XIANCHENG,CHINA,0,0,0,U,0,0,0,U,0,0.000,0.000
9298,ZYYC,NaN,NaN,YICHUN,CHINA,0,0,0,U,0,0,0,U,0,0.000,0.000
9299,ZYYJ,NaN,YANJI,YANJI,CHINA,42,52,54,N,129,26,54,E,191,42.882,129.448

In [27]:
df2 = pd.read_csv('./raw_data/BTS_Airports.csv')

df2

/tmp/ipykernel_17985/5553468.py:1: DtypeWarning: Columns (50,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('./raw_data/BTS_Airports.csv')

,the_geom,OBJECTID,Rec_Type,Site_Num,Fac_Type,Loc_Id,Eff_Date,Region_Cod,Field_Offi,State_Post,State_Name,County,County_Pos,City,Fac_Name,Owner_Type,Fac_Use,Owner_Name,Owner_Addr,Owner_City,Owner_Phon,Manager_Na,Manager_Ad,Manager_Ci,Manager_Ph,Ref_Point_,Ref_Poin_1,Ref_Poin_2,Ref_Poin_3,Ref_Poin_4,Elevation,Elevation_,Mag_Var,Mag_Var_Ye,Pattern_Al,Sectional_,Dist_City_,Dir_City_T,Land_Area_,Boundary_A,Boundary_1,Boundary_2,Responsibl,Responsi_1,Responsi_2,Fss_On_Fac,Fss_Id,Fss_Name,Local_Phon,Toll_Free_,Alt_Fss_Id,Alt_Fss_Na,Toll_Fre_1,Notam_Wx_F,Notam_DSer,Activation,Status_Cod,Arff_Cert_,Npias_Fed_,Airspace_A,Intl_Custo,Intl_Cus_1,Mil_Joint_,Mil_Landin,Inspection,Agency_Ins,Last_Inspe,Last_Info_,Fuel_Types,Repair_Ser,Power_Plan,Bottled_Ox,Bulk_Oxyge,Lighting_S,Beacon_Lig,Atc_Tower,Unicom,Ctaf,Seg_Circle,Beacon_Col,Landing_Fe,Medical_Fa,Based_Sing,Based_Mult,Based_Jet_,Based_Heli,Based_Glid,Based_Mili,Based_Ultr,Commercial,Commuter_O,Air_Taxi_O,Ga_Local_O,Ga_Itinera,Mitary_Ops,Annual_Ops,Position_S,Position_1,Elevatio_1,Elevatio_2,Contract_F,Transient_,Other_Serv,Wind_Indic,Icao_Ident,Min_Op_Net,Filler
0,POINT (-77.08511666690545 26.51012777773246),19828,APT,90727.*A,AIRPORT,MYAM,7/16/2020,NaN,NONE,NaN,NaN,BAHAMAS,BS,MARSH HARBOUR,LEONARD M THOMPSON INTL,PU,PU,NaN,NaN,NaN,NaN,DEPARTMENT OF CIVIL AVIATION,NaN,NaN,1-242-367-5500,26-30-36.4600N,095436.4600N,077-05-06.4200W,277506.4200W,E,8.0,E,08W,2010.0,NaN,MIAMI,3.0,SW,NaN,ZMA,ZCR,MIAMI,ZMA,ZCR,MIAMI,NaN,MIA,MIAMI,NaN,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,NaN,NaN,O,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,N,NaN,NaN,100 A,NaN,NaN,NaN,NaN,NaN,NaN,N,122.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIP,1/6/2010,AIP,1/6/2010,NaN,NaN,NaN,NaN,MYAM,N,NaN
1,POINT (-124.88666666664308 49.71083333275737),19748,APT,90041.*A,AIRPORT,CYQQ,7/16/2020,NaN,SEA,NaN,NaN,"B.C., CANADA",CN,COMOX,COMOX,PR,PR,CANADA,NaN,NaN,NaN,CANADIAN MILITARY,NaN,NaN,DND-250-339-8231,49-42-39.0000N,178959.0000N,124-53-12.0000W,449592.0000W,E,84.0,E,19E,NaN,NaN,SEATTLE,3.0,NNE,NaN,ZVR,ZVR,VANCOUVER,ZVR,ZVR,VANCOUVER,NaN,YKA,KAMLOOPS FIC,NaN,NaN,NaN,NaN,NaN,CYQQ,NaN,Feb-07,O,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OWNER,1/18/2007,OWNER,1/18/2007,NaN,NaN,NaN,NaN,CYQQ,N,NaN
2,POINT (-82.95764852760186 42.27586419409519),19812,APT,90506.*A,AIRPORT,CYQG,7/16/2020,NaN,NONE,NaN,NaN,"ONTARIO, CANADA",CN,WINDSOR,WINDSOR,PU,PU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42-16-33.1111N,152193.1111N,082-57-27.5347W,298647.5347W,E,622.0,E,07W,NaN,NaN,NaN,0.0,SE,NaN,ZOB,ZCC,CLEVELAND,ZOB,ZCC,CLEVELAND,NaN,YXU,LONDON FIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mar-05,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAA-EST,9/15/2011,FAA,9/15/2011,NaN,NaN,NaN,NaN,CYQG,N,NaN
3,POINT (-104.4310672224387 40.10831555601567),2815,APT,02646.63*A,AIRPORT,CO60,7/16/2020,ANM,DEN,CO,COLORADO,WELD,CO,KEENESBURG,HORSESHOE LANDINGS,PR,PR,STEVE BENSON,33245 WCR 16,"KEENSBURG, CO 80643",303-732-4483,NaN,NaN,NaN,NaN,40-06-29.9360N,144389.9360N,104-25-51.8420W,375951.8420W,E,4800.0,E,11E,1985.0,NaN,CHEYENNE,5.0,E,NaN,ZDV,ZCD,DENVER,ZDV,ZCD,DENVER,NaN,DEN,DENVER,NaN,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,N,Jul-89,O,NaN,NaN,NO OBJECTION,NaN,NaN,NaN,NaN,2,N,NaN,9072019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,N,NaN,Y,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,N,NaN
4,POINT (-97.40537083336345 46.76386333328385),10725,APT,17285.751*A,AIRPORT,8ND5,7/16/2020,AGL,DMA,ND,NORTH DAKOTA,CASS,ND,CHAFFEE,AUSK STRIP,PR,PR,HARVEY J. AUSK,NaN,"ALICE, ND 58083",701-347-4944,NaN,NaN,NaN,NaN,46-45-49.9080N,168349.9080N,097-24-19.3350W,350659.3350W,E,1020.0,E,06E,1985.0,NaN,TWIN CITIES,3.0,SW,NaN,ZMP,ZCP,MINNEAPOLIS,ZMP,ZCP,MINNEAPOLIS,N,GFK,GRAND FORKS,NaN,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,N,Dec-80,O,NaN,NaN,NO OBJECTION,NaN,NaN,NaN,NaN,2,N,NaN,5022008.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,N,NaN,N,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19845,POINT (-80.71785888857967 40.093127778074376),19581,APT,26948.1*C,SEAPLANE BASE,WV43,7/16/2020,AEA,BKW,WV,WEST VIRGINIA,OHIO,WV,WHEELING,WARWOOD - MARTINS FERRY,PR,PR,"JONES AIR, HNC.",523 S. WADESBORO BLVD,"MT. GILEAD, NC 27306",704-985-4714,DAVID E. JONES,523 S. WADESBORO BLVD,"MT. GILEAD, NC 27306",704-985-4714,40-05-35.2600N,144335.2600N,080-43-04.2920W,290584.2920W,E,623.0,E,07W,1985.0,NaN,DETROIT,3.0,S,57.0,ZOB,ZCC,CLEVELAND,ZOB,ZCC,CLEVELAND,N,EKN,ELKINS,703-724-4288,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,N,Aug-81,O,NaN,NaN,NO OBJECTION,NaN,NaN,NaN,NaN,2,N,NaN,3142014.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,N,NaN,N,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,NaN
19846,POINT (-81.39166666712309 39.11723444404222),19491,APT,26625.5*A,AIRPORT,2WV3,7/16/2020,AEA,BKW,WV,WEST VIRGINIA,WIRT,WV,ELIZABETH,HALES LANDING,PR,PR,HALES LANDING HOMEOWNERS ASSOC,PO BOX 81,"DAVISVILLE, WV 26142",NaN,HALES LANDING HO ASSN/ PRESIDENT,"STEVE RADABAUGH, PO BOX 81","DAVISVILLE, WV 26142",(304) 488-8408,39-07-02.0440N,140822.0440N,081-23-30.0000W,293010.0000W,E,650.0,E,NaN,NaN,NaN,CINCINNATI,4.0,N,5.0,ZID,ZCI,INDIANAPOLIS,ZID,ZCI,INDIANAPOLIS,NaN,EKN,ELKINS,703-724-4288,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,NaN,Sep-04,O,NaN,NaN,NO OBJECTION,NaN,NaN,NaN,NaN,2,N,NaN,8142014.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OWNER,5/24/2004,OWNER,5/24/2004,NaN,NaN,NaN,Y,NaN,N,NaN
19847,POINT (-76.17777777790917 24.891702778196635),19835,APT,90742.*A,AIRPORT,MYER,7/16/2020,NaN,NONE,NaN,NaN,BAHAMAS,BS,ROCK SOUND,ROCK SOUND,PU,PU,NaN,NaN,NaN,NaN,DEPARTMENT OF CIVIL AVIATION,NaN,NaN,1-242-334-2117,24-53-30.1300N,089610.1300N,076-10-40.0000W,274240.0000W,E,16.0,E,08W,2010.0,NaN,NaN,2.0,NNW,NaN,ZMA,ZCR,MIAMI,ZMA,ZCR,MIAMI,NaN,MIA,MIAMI,NaN,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,NaN,NaN,O,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,122.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AIP,8/28/2008,AIP,3/11/2011,NaN,NaN,CARGO,NaN,MYER,N,NaN
19848,POINT (-90.38506666712107 44.772216667281015),19359,APT,27582.*A,AIRPORT,44WI,7/16/2020,AGL,CHI,WI,WISCONSIN,CLARK,WI,SPENCER,STOIBER,PR,PR,DANIEL L. STOIBER,W1414 ROCK CREEK RD,"SPENCER, WI 54479",715-659-5121,DANIEL L. STOIBER,W1414 ROCK CREEK RD,"SPENCER, WI 54479",715-659-5121,44-46-19.9800N,161179.9800N,090-23-06.2400W,325386.2400W,E,1298.0,E,NaN,NaN,NaN,GREEN BAY,4.0,W,NaN,ZMP,ZCP,MINNEAPOLIS,ZMP,ZCP,MINNEAPOLIS,NaN,GRB,GREEN BAY,NaN,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,NaN,Mar-07,O,NaN,NaN,CONDITIONAL,NaN,NaN,NaN,NaN,2,N,NaN,1162014.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OWNER,10/3/2006,OWNER,10/3/2006,NaN,NaN,NaN,NaN,NaN,N,NaN
19849,POINT (-89.66540000022285 42.96972027811659),19227,APT,27406.87*A,AIRPORT,2WI7,7/16/2020,AGL,CHI,WI,WISCONSIN,DANE,WI,MOUNT VERNON,HECKLERS' STRIP,PR,PR,WILLIAM K GARFOOT,2161 SPRINGDALE CENTER RD,"VERONA, WI 53593",608-437-8088,WILLIAM K GARFOOT,2161 SPRINGDALE CENTER RD,"VERONA, WI 53593",608-437-8088,42-58-10.9930N,154690.9930N,089-39-55.4400W,322795.4400W,E,1130.0,E,00E,1990.0,NaN,CHICAGO,2.0,N,20.0,ZAU,ZCG,CHICAGO,ZAU,ZCG,CHICAGO,NaN,GRB,GREEN BAY,NaN,1-800-WX-BRIEF,NaN,NaN,NaN,NaN,N,Aug-94,O,NaN,NaN,CONDITIONAL,NaN,NaN,NaN,NaN,2,N,NaN,4132018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,N,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,N,NaN

#### Filtering datasets

In [28]:
df1 = df1[df1['Country'] == 'USA']

df1 = df1.dropna(subset=['Airport Name'])

to_keep = [
    'Airport Name',
    'City/Town',
    'Latitude Decimal Degrees',
    'Longitude Decimal Degrees'
]

df1 = df1[to_keep]

df1 = df1.rename(columns={'Airport Name': 'Name',
                          'City/Town': 'City',
                          'Latitude Decimal Degrees': 'Latitude',
                          'Longitude Decimal Degrees': 'Longitude',
                          })

df1

                             Name            City  Latitude  Longitude
3380                 ABILENE RGNL         ABILENE    32.411    -99.682
3382                NANTUCKET MEM       NANTUCKET    41.253    -70.060
3383                    WACO RGNL            WACO    31.611    -97.230
3384  ATLANTIC CITY INTERNATIONAL   ATLANTIC CITY    39.458    -74.577
3385                 ARDMORE MUNI         ARDMORE    34.303    -97.019
...                           ...             ...       ...        ...
6669                 BRADSHAW AAF  BRADSHAW FIELD    19.760   -155.554
6670           HILO INTERNATIONAL            HILO    19.720   -155.049
6671                        UPOLU           OPOLU    20.265   -155.860
6685                 OLIKTOK LRRS   OLIKTOK POINT    70.499   -149.879
6686               POINT LAY LRRS       POINT LAY    69.733   -163.005

[486 rows x 4 columns]

In [29]:
df2 = df2[df2['Fac_Type'] == 'AIRPORT']

df2 = df2[~df2['State_Post'].isin(['AK', 'HI'])]

# These are mostly islands (not accessible for drivers)
df2 = df2.dropna(subset=['State_Post'])

# Drop unnecessary columns
to_keep = [
    'the_geom',
    'Fac_Name',
    'State_Post',
    'City'
]

df2 = df2[to_keep]

df2 = df2.rename(columns={'Fac_Name': 'Name',
                          'State_Post': 'State',
                          })

df2[['Longitude', 'Latitude']] = df2['the_geom'].str.extract(r'POINT \(([-\d\.]+) ([-\d\.]+)\)')

df2[['Longitude', 'Latitude']] = df2[['Longitude', 'Latitude']].astype(float)

df2 = df2.drop(labels='the_geom', axis=1)

df2

,Name,State,City,Longitude,Latitude
3,HORSESHOE LANDINGS,CO,KEENESBURG,-104.431067,40.108316
4,AUSK STRIP,ND,CHAFFEE,-97.405371,46.763863
5,LAKE VILLAGE,MO,PARIS,-92.010448,39.460594
7,SCOTT AIRSTRIP,MI,LAKE,-85.023919,43.864189
8,TELFORD OVERLOOK FERGUSON FIELD,TN,TELFORD,-82.539567,36.208733
...,...,...,...,...,...
19843,SHELL LAKE MUNI,WI,SHELL LAKE,-91.920661,45.731381
19844,KINKY CREEK DIVIDE,WY,DUBOIS,-110.109896,43.375499
19846,HALES LANDING,WV,ELIZABETH,-81.391667,39.117234
19848,STOIBER,WI,SPENCER,-90.385067,44.772217
19849,HECKLERS' STRIP,WI,MOUNT VERNON,-89.665400,42.969720

### Finding the intersection on Longitude and Latitude

This is mainly to filter out minor airports in `df1` while retaining the state and city names

In [30]:
from geopy.distance import great_circle

def find_nearby_airports(df1, df2, radius=2):
    matches = []
    
    for _, row1 in df1.iterrows():
        lat1, lon1 = row1['Latitude'], row1['Longitude']
        
        for _, row2 in df2.iterrows():
            lat2, lon2 = row2['Latitude'], row2['Longitude']
            distance = great_circle((lat1, lon1), (lat2, lon2)).miles  # Calculate distance in miles
            
            if distance <= radius:
                matches.append({
                    'df1_Name': row1['Name'],
                    'df1_City': row1['City'],
                    'df2_Name': row2['Name'],
                    'df2_City': row2['City'],
                    'df2_State': row2['State'],
                    'Longitude': row2['Longitude'],
                    'Latitude': row2['Latitude'],
                })
    
    return pd.DataFrame(matches)

# Find matches within 1 mile
df = find_nearby_airports(df1, df2)

df

,df1_Name,df1_City,df2_Name,df2_City,df2_State,Longitude,Latitude
0,ABILENE RGNL,ABILENE,ABILENE RGNL,ABILENE,TX,-99.681889,32.411333
1,NANTUCKET MEM,NANTUCKET,NANTUCKET MEMORIAL,NANTUCKET,MA,-70.059911,41.252975
2,WACO RGNL,WACO,WACO RGNL,WACO,TX,-97.230306,31.612194
3,ATLANTIC CITY INTERNATIONAL,ATLANTIC CITY,ATLANTIC CITY INTL,ATLANTIC CITY,NJ,-74.577167,39.457583
4,ARDMORE MUNI,ARDMORE,ARDMORE MUNI,ARDMORE,OK,-97.020597,34.303873
...,...,...,...,...,...,...,...
407,MC GUIRE AFB,WRIGHTSTOWN,MC GUIRE FLD (JOINT BASE MC GUIRE DIX LAKEHURST),WRIGHTSTOWN,NJ,-74.591699,40.015584
408,CAPE MAY CO,WILDWOOD,CAPE MAY COUNTY,WILDWOOD,NJ,-74.908511,39.008369
409,WILLOW RUN,DETROIT,WILLOW RUN,DETROIT,MI,-83.530889,42.240028
410,YOUNGSTOWN WARREN RGNL,YOUNGSTOWN,YOUNGSTOWN-WARREN RGNL,YOUNGSTOWN/WARREN,OH,-80.680361,41.261583
411,YUMA MCAS YUMA INTERNATIONAL,YUMA,YUMA MCAS/YUMA INTL,YUMA,AZ,-114.605987,32.656574

In [37]:
# Formatting

df = df.rename(columns={
    'df1_Name': 'Name',
    'df2_City': 'City',
    'df2_State': 'State',
})

df = df[['Name', 'City', 'State', 'Longitude', 'Latitude']]

df

,Name,City,State,Longitude,Latitude
0,ABILENE RGNL,ABILENE,TX,-99.681889,32.411333
1,NANTUCKET MEM,NANTUCKET,MA,-70.059911,41.252975
2,WACO RGNL,WACO,TX,-97.230306,31.612194
3,ATLANTIC CITY INTERNATIONAL,ATLANTIC CITY,NJ,-74.577167,39.457583
4,ARDMORE MUNI,ARDMORE,OK,-97.020597,34.303873
...,...,...,...,...,...
407,MC GUIRE AFB,WRIGHTSTOWN,NJ,-74.591699,40.015584
408,CAPE MAY CO,WILDWOOD,NJ,-74.908511,39.008369
409,WILLOW RUN,DETROIT,MI,-83.530889,42.240028
410,YOUNGSTOWN WARREN RGNL,YOUNGSTOWN/WARREN,OH,-80.680361,41.261583
411,YUMA MCAS YUMA INTERNATIONAL,YUMA,AZ,-114.605987,32.656574

In [39]:
df.to_csv('data/Airports.csv', index=False)