In [8]:
import pandas as pd

pd.set_option('display.max_columns', None)

pd.set_option('display.max_rows', 100)

df = pd.read_csv('./raw_data/Hospitals.csv')

to_drop = [
    'X',
    'Y',
    'TYPE',
    'OBJECTID',
    'ID',
    'ZIP4',
    'TELEPHONE',
    'COUNTYFIPS',
    'NAICS_CODE',
    'NAICS_DESC',
    'SOURCE',
    'SOURCEDATE',
    'VAL_METHOD',
    'VAL_DATE',
    'WEBSITE',
    'STATE_ID',
    'ST_FIPS',
    'OWNER',
    'TTL_STAFF',
    'BEDS',
    'TRAUMA',
    'HELIPAD'
    ]

df = df.drop(to_drop, axis=1)

df

,NAME,ADDRESS,CITY,STATE,ZIP,STATUS,POPULATION,COUNTY,COUNTRY,LATITUDE,LONGITUDE,ALT_NAME
0,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXAND...,1700 JAMES BOWIE DRIVE,BAYTOWN,TX,77520,OPEN,182,HARRIS,USA,29.747620,-94.945477,NOT AVAILABLE
1,"WOODS AT PARKSIDE,THE",349 OLDE RIDENOUR ROAD,COLUMBUS,OH,43230,OPEN,50,FRANKLIN,USA,40.027143,-82.881843,NOT AVAILABLE
2,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,OPEN,155,MONTGOMERY,USA,39.774242,-84.168027,NOT AVAILABLE
3,VIBRA HOSPITAL OF MAHONING VALLEY,8049 SOUTH AVENUE,BOARDMAN,OH,44512,OPEN,45,MAHONING,USA,41.005169,-80.632972,MAHONING VALLEY HOSPITAL BOARDMAN CAMPUS
4,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,"ONE ELIZABETH PLACE,E3 SUITE A",DAYTON,OH,45417,OPEN,32,MONTGOMERY,USA,39.747740,-84.199398,NOT AVAILABLE
...,...,...,...,...,...,...,...,...,...,...,...,...
7565,LIFE LINE HOSPITAL,200 SCHOOL STREET,WINTERSVILLE,OH,43953,OPEN,36,JEFFERSON,USA,40.372434,-80.701221,NOT AVAILABLE
7566,"TEN LAKES CENTER, LLC","819 NORTH FIRST STREET,3RD FLOOR",DENNISON,OH,44621,OPEN,16,TUSCARAWAS,USA,40.401257,-81.336345,NOT AVAILABLE
7567,LINDNER CENTER OF HOPE,4075 OLD WESTERN ROW ROAD,MASON,OH,45040,OPEN,34,WARREN,USA,39.331523,-84.294586,NOT AVAILABLE
7568,CUERO COMMUNITY HOSPITAL,2550 NORTH ESPLANADE STREET,CUERO,TX,79022,OPEN,49,DEWITT,USA,29.112615,-97.283341,NOT AVAILABLE
7569,HARRIS HEALTH SYSTEM QUENTIN MEASE HOSPITAL,3601 NORTH MACGREGOR WAY,HOUSTON,TX,77004,OPEN,49,HARRIS,USA,29.711039,-95.359806,NOT AVAILABLE

#### Remove closed hospitals

In [9]:
df = df[df['STATUS'] == 'OPEN']

df = df[df['COUNTRY'] == 'USA']

states_to_keep = [ 'AL','AZ','AR','CA','CO','CT','DE','FL','GA','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
                   'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY' ]

df = df[df['STATE'].isin(states_to_keep)]

In [10]:


df

,NAME,ADDRESS,CITY,STATE,ZIP,STATUS,POPULATION,COUNTY,COUNTRY,LATITUDE,LONGITUDE,ALT_NAME
0,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXAND...,1700 JAMES BOWIE DRIVE,BAYTOWN,TX,77520,OPEN,182,HARRIS,USA,29.747620,-94.945477,NOT AVAILABLE
1,"WOODS AT PARKSIDE,THE",349 OLDE RIDENOUR ROAD,COLUMBUS,OH,43230,OPEN,50,FRANKLIN,USA,40.027143,-82.881843,NOT AVAILABLE
2,DAYTON CHILDREN'S HOSPITAL,ONE CHILDRENS PLAZA,DAYTON,OH,45404,OPEN,155,MONTGOMERY,USA,39.774242,-84.168027,NOT AVAILABLE
3,VIBRA HOSPITAL OF MAHONING VALLEY,8049 SOUTH AVENUE,BOARDMAN,OH,44512,OPEN,45,MAHONING,USA,41.005169,-80.632972,MAHONING VALLEY HOSPITAL BOARDMAN CAMPUS
4,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,"ONE ELIZABETH PLACE,E3 SUITE A",DAYTON,OH,45417,OPEN,32,MONTGOMERY,USA,39.747740,-84.199398,NOT AVAILABLE
...,...,...,...,...,...,...,...,...,...,...,...,...
7565,LIFE LINE HOSPITAL,200 SCHOOL STREET,WINTERSVILLE,OH,43953,OPEN,36,JEFFERSON,USA,40.372434,-80.701221,NOT AVAILABLE
7566,"TEN LAKES CENTER, LLC","819 NORTH FIRST STREET,3RD FLOOR",DENNISON,OH,44621,OPEN,16,TUSCARAWAS,USA,40.401257,-81.336345,NOT AVAILABLE
7567,LINDNER CENTER OF HOPE,4075 OLD WESTERN ROW ROAD,MASON,OH,45040,OPEN,34,WARREN,USA,39.331523,-84.294586,NOT AVAILABLE
7568,CUERO COMMUNITY HOSPITAL,2550 NORTH ESPLANADE STREET,CUERO,TX,79022,OPEN,49,DEWITT,USA,29.112615,-97.283341,NOT AVAILABLE
7569,HARRIS HEALTH SYSTEM QUENTIN MEASE HOSPITAL,3601 NORTH MACGREGOR WAY,HOUSTON,TX,77004,OPEN,49,HARRIS,USA,29.711039,-95.359806,NOT AVAILABLE

In [11]:
df = df.rename(columns={
    'NAME': 'Name',
    'CITY': 'City',
    'STATE': 'State',
    'LONGITUDE': 'Longitude',
    'LATITUDE': 'Latitude',
})

df = df[['Name', 'City', 'State', 'Longitude', 'Latitude']]

df

,Name,City,State,Longitude,Latitude
0,HOUSTON METHODIST SAN JACINTO HOSPITAL ALEXAND...,BAYTOWN,TX,-94.945477,29.747620
1,"WOODS AT PARKSIDE,THE",COLUMBUS,OH,-82.881843,40.027143
2,DAYTON CHILDREN'S HOSPITAL,DAYTON,OH,-84.168027,39.774242
3,VIBRA HOSPITAL OF MAHONING VALLEY,BOARDMAN,OH,-80.632972,41.005169
4,HAVEN BEHAVIORAL SENIOR CARE OF DAYTON,DAYTON,OH,-84.199398,39.747740
...,...,...,...,...,...
7565,LIFE LINE HOSPITAL,WINTERSVILLE,OH,-80.701221,40.372434
7566,"TEN LAKES CENTER, LLC",DENNISON,OH,-81.336345,40.401257
7567,LINDNER CENTER OF HOPE,MASON,OH,-84.294586,39.331523
7568,CUERO COMMUNITY HOSPITAL,CUERO,TX,-97.283341,29.112615
7569,HARRIS HEALTH SYSTEM QUENTIN MEASE HOSPITAL,HOUSTON,TX,-95.359806,29.711039

In [12]:
df.to_csv('./data/Hospitals.csv', index=False)